version: '3.4'


services:
  gateaway.api:
    image: ${DOCKER_REGISTRY-}gateawayapi
    build:
      context: .
      dockerfile: GateAway.Api/Dockerfile

  gai.api:
    image: ${DOCKER_REGISTRY-}gaiapi
    build:
      context: .
      dockerfile: GAI.Api/Dockerfile


  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    volumes:
      - c:\mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"
