version: '3.4'

networks:
  backend:

services:
  gateaway.api:
    image: ${DOCKER_REGISTRY-}gateawayapi
    build:
      context: .
      dockerfile: GateAway.Api/Dockerfile

  gai.api:
    image: ${DOCKER_REGISTRY-}gaiapi
    build:
      context: .
      dockerfile: GAI.Api/Dockerfile

  olx.api:
    image: ${DOCKER_REGISTRY-}olxapi
    build:
      context: .
      dockerfile: OLX.Api/Dockerfile
