version: '3.4'

networks:
  backend:

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    volumes:
      - c:\mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"

  gateaway.api:
    image: ${DOCKER_REGISTRY-}gateawayapi
    build:
      context: .
      dockerfile: GateAway.Api/Dockerfile
    ports:
        - 7080:80
    networks:
        - backend
  gai.api:
    image: ${DOCKER_REGISTRY-}gaiapi
    build:
      context: .
      dockerfile: GAI.Api/Dockerfile

  olx.api:
    image: ${DOCKER_REGISTRY-}olxapi
    build:
      context: .
      dockerfile: OLX.Api/Dockerfile


  yandextaxi.api:
    image: ${DOCKER_REGISTRY-}yandextaxiapi
    build:
      context: .
      dockerfile: YandexTaxi.Api/Dockerfile

